### ISSUE TITLE
Test for User complete 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Courses#132]
Test if 

- once all progress as set as complete there should be event fired `CourseCompleted` https://github.com/EscolaLMS/Courses/blob/801d593a6351139467931f578cb375df118ec415/src/Services/ProgressService.php#L64
- now course should be listed as finished (this is renederd on frontend based on `progress` endpoint)
-

**Comment by pa-cholek** [comment]
I've changed one of the tests to check if `CourseCompleted` event is triggered when `ProgressService::update` is called and it works

```
            $user->courses()->updateExistingPivot($course->getKey(), ['finished' => true]);
            event(new CourseCompleted($courseProgressCollection->getCourse(), $user));
```

but as you can see triggering that event has nothing to do with changing the `finished` boolean, it's done separately. Maybe we should move triggering that event to Course updated/saved event, so it triggers automatically when course is marked as finished?

**Comment by qunabu** [comment]
you can do this, but this is not critical imho

**Comment by pa-cholek** [comment]
I'll think about that, I've removed "high priority" label for now
