### ISSUE TITLE
h5p saved in two subjects

### ISSUE THREAD

**Issue by victazzz** [EscolaLMS/Courses#146]
we have a lesson with two subjects that already have a h5p, we want to override the h5p element in the 2nd topic by 

![image](https://user-images.githubusercontent.com/24989821/139436146-289b67c6-8aef-47a0-b131-1332cb6786af.png)

when the item is uploaded we get the id of the new item 
![image](https://user-images.githubusercontent.com/24989821/139436511-f99f1680-8a27-4418-ac19-8db3edead585.png)

and we save the status of the topic with valid ids.

![image](https://user-images.githubusercontent.com/24989821/139436610-0113024c-a853-4a42-bb82-29206bc7dc0d.png)

after a refresh h5p changes in both subjects

![image](https://user-images.githubusercontent.com/24989821/139436895-465bc5e4-a03e-48ef-af2b-defb6b9c535d.png)

**Comment by qunabu** [comment]
can't reproduce
