### ISSUE TITLE
are files saved to `course/{id}` folder

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Courses#152]
please double check that 

- [x] each course/topic/lesson files are saved into `course/{id}` folder
- [x] once course is deleted everything is deleted from that folder as well 
- [ ] this should be disk agnostic, should work on localstorage and s3 and othe laravel disks providers

**Comment by KrzysztofDziedziechEscolasoft** [comment]
https://i.imgur.com/bVfGzsl.png

link on s3 is good
