### ISSUE TITLE
swagger fails 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Courses#209]
https://github.com/EscolaLMS/Courses/runs/4896685333?check_suite_focus=true

**Comment by qunabu** [comment]
possible solution 

1. before running vendor/bin/openapi copy vendor/escolalms/auth/src/models/user.php to main folder 
2. add the folder of auth somehow to openapi https://zircote.github.io/swagger-php/Getting-started.html#cli

**Comment by pa-cholek** [comment]
Or we can just add User Swagger Schema to Courses User model...

**Comment by qunabu** [comment]
> Or we can just add User Swagger Schema to Courses User model...

then it would conflict in API when building from all blocks

**Comment by pa-cholek** [comment]
I don't really understand though why this warning appears only for CourseAPISwagger.php, when same ref is used in CourseAccessAPISwagger

**Comment by pa-cholek** [comment]
Fixed this by including `./vendor/escolalms/auth/models` in scanned directories for swagger generation
